add transport class with fields, comparable, delivery time and delive…
Vladholovchak/delivery_lib pull request #1
Opened 2021-08-19 18:51 UTC by Vladholovchak

…ry speed methods; add child classes car and bike; add module with constants

2021-08-23 10:49 UTC, averevkin commented
Не вижу класса DeliveryService

2021-08-23 17:34 UTC, Vladholovchak commented
> Не вижу класса DeliveryService

Не доделал ещё, к остальным нет замечаний?

2021-08-24 16:20 UTC, Vladholovchak commented
> Не вижу класса DeliveryService

Дописал DeliveryService

2021-08-25 09:40 UTC, averevkin requested changes

2021-08-25 09:40 UTC, averevkin commented on transport.rb
> +    delivery_speed <=> other.delivery_speed
Это не ошибка, но в задании хотелось бы видеть решение без использования <=>, для понимания как работет этот опратор.

2021-08-25 09:40 UTC, averevkin commented on bike.rb
> +    @max_weight = MAX_BIKE_WEIGHT
Т.к. max_weight, speed и available являются общими для Car и Bike, то необходимо их инициализацию перенести в конструктор этого класса, а тут только переиспользовать его

2021-08-25 09:40 UTC, averevkin commented on delivery_service.rb
> +    amount.times { @park << transport }
я бы переписал без использования times:
```ruby
new_transport = Array.new(amount) { transport }
@park += new_transport
```

2021-08-25 09:40 UTC, averevkin commented on delivery_service.rb
> +    @transport.select!(&:available)
Рекомендуется делать функции максимально иммутабельными. Идея метода find_available_transport хорошая, но я бы возвращал тут @park.select(&:available), а в @transport записывал бы в find_transport методе

2021-08-25 13:51 UTC, averevkin commented on transport.rb
> +  def initialize
Transport.new работать не будет. Надо сюда передавать значения max_weight и speed

2021-08-25 13:51 UTC, averevkin commented on car.rb
> +    super
Надо сюда передавать значения max_weight и speed

2021-08-25 13:51 UTC, averevkin commented on bike.rb
> +    super
Надо сюда передавать значения max_weight и speed

2021-08-25 13:52 UTC, merged

2021-08-25 14:16 UTC, Vladholovchak commented on transport.rb
> +  def initialize
Та вроде работает)
#<Transport:0x00007ffdd6853140 @available=true>