refactor constants module
Vladholovchak/delivery_lib pull request #2
Opened 2021-08-30 20:33 UTC by Vladholovchak

2021-09-02 09:07 UTC, averevkin requested changes

2021-09-02 09:07 UTC, averevkin commented on spec/transport_spec.rb
> +class MotorBike < Transport
Не надо создавать отдельные вымышленные классы для тестирования. По сути ваш тест проверяет сравнения MotorBike и CosmoBike которые существуют только в тестах и не используются в реальном приложении

2021-09-02 09:07 UTC, averevkin commented on spec/transport_spec.rb
> +      expect(bike == motorbike).to be_truthy
1) используйте https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/equality-matchers чтобы проверять условия
2) старайтесь делать тест кейсы с 1 expect внутри и если у них одинаковые тестовые данные, объеденяйте их в контексты

2021-09-02 09:07 UTC, averevkin commented on spec/transport_spec.rb
> +  context '#comparable' do
1) это должен быть describe блок
2) когда вы пишете #comparable это значит что у истанса вашего класса есть метод comparable, что не правда.
По сути структура вашего теста должна быть такова

describe Transport do
  describe '<=>' do
    context 'with different class with same attributes'
    context 'with same class and different attributes'
    context 'when same max_weight'

2021-09-02 09:07 UTC, averevkin commented on lib/delivery_service.rb
> +class DeliveryService
Не вижу тестов для этого класса

2021-09-02 09:07 UTC, averevkin commented on lib/transport.rb
> +    @max_distance || Float::INFINITY
@max_distance это атрибут класса Bike и Transport про него ничего не знает. Вы должны проверять в <=> отвечает ли сравниваемые экземпляры на max_distance. Данная же реализация, делает наследование бессмысленным

2021-09-06 07:23 UTC, Vladholovchak commented on spec/transport_spec.rb
> +class MotorBike < Transport
Я хотів покрити майбутні випадки, коли буде більше різноматніх child класу Transport, адже методу  <=> не важливі які саме будуть дочірні класи і можна перевірити більше варіантів порівняння, ніж з car i bike, де атрибути константи. Типу теж порівняння за max_distance не буде використовуватись, так як max_weigth різна у car i bike, а  bike  з різними max_distance теж не буде

2021-09-06 09:14 UTC, Vladholovchak commented on spec/transport_spec.rb
> +class MotorBike < Transport
> Не надо создавать отдельные вымышленные классы для тестирования. По сути ваш тест проверяет сравнения MotorBike и CosmoBike которые существуют только в тестах и не используются в реальном приложении

можливо потрібно додати можливість задавати всі атрибути при створенні об'єктів класів Transport, Car, Bike?
тоді можна буде краще покрити все тестами

2021-09-06 09:28 UTC, averevkin commented on spec/transport_spec.rb
> +class MotorBike < Transport
Якщо ми кажемо що в нас немає інтерфейсу створення классів з довільними атрибутами(а є тільки за замовченням), то і тестувати це немає необхідності. Бо так ми будемо створювати функціональності які бізнесу не потрібні

2021-09-07 20:15 UTC, merged