Dev
Vladholovchak/delivery_lib pull request #3
Opened 2021-09-08 06:54 UTC by Vladholovchak

2021-09-08 08:05 UTC, averevkin requested changes
I don't see tests for new methods you have implemented

2021-09-08 08:05 UTC, averevkin commented on lib/transport.rb
> +  @@instances = []
It is better to use instance variables of the class rather than class variables. See: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/ClassVars

2021-09-08 08:50 UTC, Vladholovchak commented
> I don't see tests for new methods you have implemented

It's steel in progress,  I added some few minutes ago. I am planning to finish it during the day

2021-09-08 08:54 UTC, Vladholovchak commented on lib/transport.rb
> +  @@instances = []
I used instance variable, but it's value always nil if it isn't in initialize method

2021-09-12 16:45 UTC, averevkin approved these changes

2021-09-12 18:22 UTC, merged